name: Daily task

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          packages: package
          requirements: requirements.txt

      - name: Run a multi-line script
        run: |
          python main.py --method='S1_METHOD' --url='S1_URL' --host='S1_HOST' --cookie='S1_COOKIE' --al='S1_AL' --ua='S1_UA' --referer='S1_REFERER' --result='S1_RESULT'
