name: Daily task

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: Run a multi-line script
        run: |
          python main.py --wc='${{ secrets.WC_URL }}' --title='${{ secrets.S1_TITLE }}' --method='${{ secrets.S1_METHOD }}' --url='${{ secrets.S1_URL }}' --host='${{ secrets.S1_HOST }}' --cookie='${{ secrets.S1_COOKIE }}' --al='${{ secrets.S1_AL }}' --ua='${{ secrets.S1_UA }}' --referer='${{ secrets.S1_REFERER }}' --result='${{ secrets.S1_RESULT }}'
