name: Daily task S1

on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: Run a multi-line script
        run: |
          python main.py --wc='${{ secrets.WC_URL }}' --title='${{ secrets.S2_TITLE }}' --method='${{ secrets.S2_METHOD }}' --url='${{ secrets.S2_URL }}' --host='${{ secrets.S2_HOST }}' --cookie='${{ secrets.S2_COOKIE }}' --al='${{ secrets.S2_AL }}' --ua='${{ secrets.S2_UA }}' --referer='${{ secrets.S2_REFERER }}' --result='${{ secrets.S2_RESULT }}' --payload='${{ secrets.S2_PAYLOAD }}'
